apiVersion: batch/v1
kind: Job
metadata:
  name: log-analyzer-job
spec:
  template:
    spec:
      containers:
        - name: log-analyzer
          image: samuelmatos97/log-analyzer:latest
          imagePullPolicy: Always
      restartPolicy: Never
